spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/piccolos_db
spring.datasource.username=piccolos_admin
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
server.port=8081
